### ISSUE TITLE
Using 'both' or 'toggle' not working (Ubuntu 24.04)

### ISSUE THREAD

**Issue by awesomebytes** [alesya-h/zenbook-duo-2024-ux8406ma-linux#4]
Hello!

Thanks a lot for your work, it is extremely appreciated that I could start using such modern hardware and someone did all this hard work already!

I am trying to get the toggle to work (when attaching/detaching the keyboard), however, it is not currently working. If I try to do `duo both` or `duo toggle` it does not work (nothing happens) and I get the following errors:
```bash
sam@lzas:~$ duo both
:::: ../src/gmc-display-config.c:691 cc_display_logical_monitor_config_add_monitor() - 
:::: ../src/gmc-display-config.c:691 cc_display_logical_monitor_config_add_monitor() - 
Logical monitor [ 2880x1800+0+0 ], PRIMARY, scale = 1.74757
  Monitor [ eDP-1 ] 2880x1800@120
Logical monitor [ 2880x1800+0+1030 ], scale = 1.74757
  Monitor [ eDP-2 ] 2880x1800@120
[(0, 0, 2.0, uint32 0, true, [('eDP-1', '2880x1800@120.000', @a{sv} {})]), (0, 1030, 2.0, 0, false, [('eDP-2', '2880x1800@120.000', {})])]
Failed to set configuration: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Logical monitors not adjacent

sam@lzas:~$ duo toggle
:::: ../src/gmc-display-config.c:691 cc_display_logical_monitor_config_add_monitor() - 
:::: ../src/gmc-display-config.c:691 cc_display_logical_monitor_config_add_monitor() - 
Logical monitor [ 2880x1800+0+0 ], PRIMARY, scale = 1.74757
  Monitor [ eDP-1 ] 2880x1800@120
Logical monitor [ 2880x1800+0+1030 ], scale = 1.74757
  Monitor [ eDP-2 ] 2880x1800@120
[(0, 0, 2.0, uint32 0, true, [('eDP-1', '2880x1800@120.000', @a{sv} {})]), (0, 1030, 2.0, 0, false, [('eDP-2', '2880x1800@120.000', {})])]
Failed to set configuration: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Logical monitors not adjacent
```

I can, however, do `duo bottom` and `duo top` and they work.
Any help on debugging this would be greatly appreciated.

Edit: in case it matters, my kernel is: Linux lzas 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Update: I can still enable the display via the settings GUI, however, it does lose the relative position of the screen configuration. Maybe this is a bit of a hint that can help?

**Comment by Aziiz1989** [comment]
I had the same issue. it turns out my y_offset is not correct. I changed it to 1800 and it worked. I got the number from doing bustle recording. I have the 3k version btw

**Comment by awesomebytes** [comment]
Awesome! I'll try tomorrow, thanks!

**Comment by alesya-h** [comment]
I also have a 3k version. The problem for both of you seems to be that you don't have the fractional scaling feature enabled (you need to add `'scale-monitor-framebuffer'` into the array at `/org/gnome/mutter/experimental-features` in dconf), so instead of using a proper fractional scaling factor at 1.74 it falls back to 2.0 and with that the offset is different.

**Comment by Aziiz1989** [comment]
@alesya-h that did work! thank you

**Comment by awesomebytes** [comment]
That worked, indeed! Thank you @alesya-h

**Comment by NaScha** [comment]
I have 2 different installations (both Ubuntu 24.04). With one of them, it works with this mutter experimental feature activated, with the other one, it doesn't (no effect, still the same errors like @awesomebytes). Any idea what else can be done to bypass these errors?

// Edit
The installation the mutter experimental feature activation did not help for could be repaired by the hint of @Aziiz1989. Strange thing, that 2 different installations of the same OS do behave so differently.
